FROM ubuntu:26.04

RUN apt-get update && \
    apt-get -y install \
        build-essential \
        curl \
        gdb \
        git \
        libcairo2-dev \
        libegl-dev \
        libgles-dev \
        libwayland-dev \
        mangohud \
        meson \
        pkg-config \
        valgrind \
        wayland-protocols

RUN curl -sSL https://apt.llvm.org/llvm-snapshot.gpg.key | tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc && \
    echo "deb http://apt.llvm.org/resolute/ llvm-toolchain-resolute main" | tee /etc/apt/sources.list.d/llvm.list && \
    apt-get update && \
    apt-get -y install clang-format

RUN apt-get -y clean && \
    rm -rf /var/lib/apt/lists/*

RUN userdel -f -r ubuntu
