FROM ubuntu:25.10

RUN apt update && \
    apt -y install \
        build-essential \
        gdb \
        git \
        libcairo2-dev \
        libegl-dev \
        libgles-dev \
        libwayland-dev \
        meson \
        pkg-config \
        valgrind \
        wayland-protocols && \
    apt -y clean && \
    rm -rf /var/lib/apt/lists/*
