FROM mcr.microsoft.com/devcontainers/base:noble

RUN apt update && \
    apt -y install \
        build-essential \
        gdb \
        libcairo2-dev \
        libwayland-dev \
        meson \
        pkg-config \
        valgrind \
        wayland-protocols
